name: Run Python Script Every 15 Seconds

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every minute

jobs:
  run_script:
    runs-on: ubuntu-latest  # You can change the runner OS as per your requirement
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your repository's code
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Replace with your desired Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements
    
    - name: Run Python script
      run: python mqtt.py  # Replace with the path to your Python script
